import React from 'react';

interface WeeklyLogbookPreviewProps {
  content: string;
  dateRange: string;
}

export const WeeklyLogbookPreview: React.FC<WeeklyLogbookPreviewProps> = ({ content, dateRange }) => {
  return (
    <div 
      id="logbook-preview" 
      className="p-8 sm:p-12 bg-white text-slate-900 shadow-inner rounded-2xl border border-slate-200 min-h-[800px] font-sans flex flex-col"
    >
      {/* Official Header */}
      <div className="border-b-2 border-slate-900 pb-6 mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-black uppercase tracking-tight text-slate-900">Weekly Internship Logbook</h1>
          <p className="text-sm font-bold text-indigo-600 mt-1 uppercase tracking-widest">Professional Engineering Record</p>
        </div>
        <div className="text-right">
          <p className="text-[10px] font-black uppercase tracking-widest text-slate-400">Duration</p>
          <p className="text-sm font-bold text-slate-800">{dateRange}</p>
        </div>
      </div>

      {/* Report Content */}
      <div className="flex-1">
        <div className="whitespace-pre-wrap text-base leading-relaxed text-slate-800 space-y-4 font-medium">
          {/* Simple hack to render markdown-like bolding if the AI uses **text** */}
          {content.split('\n').map((line, i) => {
             const parts = line.split(/(\*\*.*?\*\*)/g);
             return (
               <p key={i}>
                 {parts.map((part, j) => {
                   if (part.startsWith('**') && part.endsWith('**')) {
                     return <strong key={j} className="font-black text-slate-900">{part.slice(2, -2)}</strong>;
                   }
                   return part;
                 })}
               </p>
             );
          })}
        </div>
      </div>

      {/* Signature Section */}
      <div className="mt-20 pt-12 border-t border-slate-200 grid grid-cols-2 gap-12">
        <div className="space-y-8">
          <div className="h-px bg-slate-400 w-full mb-2"></div>
          <div>
            <p className="text-[10px] font-black uppercase tracking-widest text-slate-400">Intern Signature</p>
            <p className="text-sm font-bold text-slate-800 mt-1">Date: ________________</p>
          </div>
        </div>
        <div className="space-y-8">
          <div className="h-px bg-slate-400 w-full mb-2"></div>
          <div>
            <p className="text-[10px] font-black uppercase tracking-widest text-slate-400">Industry Supervisor Signature</p>
            <p className="text-sm font-bold text-slate-800 mt-1">Date: ________________</p>
          </div>
        </div>
      </div>

      {/* Footer / Disclaimer */}
      <div className="mt-12 pt-6 border-t border-slate-100 text-[9px] font-bold text-slate-400 uppercase tracking-widest text-center">
        This document is automatically generated by Daily Standup AI Engine • Confidential Engineering Record
      </div>
    </div>
  );
};
